package cli

import (
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// The README's CLI reference drifted badly once: it was missing five
// commands and several flags, and still described shipped features as
// future work. Prose drifts because nothing checks it — so this checks
// it.
//
// The test lives here rather than in CI shell so it fails on `go test`
// before a push, which is when the author still has the context to fix
// it cheaply.

// cobraBuiltins are generated by cobra itself, not authored surface, so
// documenting them would be noise.
var cobraBuiltins = map[string]bool{
	"help":       true,
	"completion": true,
}

// flagsExemptFromDocs are universal and documenting them per-command
// would bloat the reference without informing anyone.
var flagsExemptFromDocs = map[string]bool{
	"help": true,
}

func readmeCLIBlock(t *testing.T) string {
	t.Helper()
	path := filepath.Join("..", "..", "README.md")
	body, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read README: %v", err)
	}
	s := string(body)
	i := strings.Index(s, "\n## CLI")
	if i < 0 {
		t.Fatal("README has no `## CLI` section — the reference this test guards is gone")
	}
	rest := s[i:]
	// The section's first fenced block is the command reference.
	start := strings.Index(rest, "```")
	if start < 0 {
		t.Fatal("`## CLI` section has no fenced code block")
	}
	rest = rest[start+3:]
	end := strings.Index(rest, "```")
	if end < 0 {
		t.Fatal("unterminated fenced block in the `## CLI` section")
	}
	return rest[:end]
}

// walk collects every command and its locally-defined flags.
func walk(c *cobra.Command, into map[string][]string) {
	for _, sub := range c.Commands() {
		name := sub.Name()
		if cobraBuiltins[name] {
			continue
		}
		var flags []string
		sub.LocalFlags().VisitAll(func(f *pflag.Flag) {
			if flagsExemptFromDocs[f.Name] {
				return
			}
			flags = append(flags, f.Name)
		})
		into[name] = flags
		walk(sub, into)
	}
}

// TestREADMEDocumentsEveryCommand fails when a command exists on the
// root but never appears in the README's CLI reference.
func TestREADMEDocumentsEveryCommand(t *testing.T) {
	block := readmeCLIBlock(t)
	cmds := map[string][]string{}
	walk(NewRootCmd(), cmds)

	var missing []string
	for name := range cmds {
		// Match `weftly <name>` at the start of a reference line.
		re := regexp.MustCompile(`(?m)^weftly ` + regexp.QuoteMeta(name) + `\b`)
		if !re.MatchString(block) {
			missing = append(missing, name)
		}
	}
	sort.Strings(missing)
	if len(missing) > 0 {
		t.Errorf("README `## CLI` block does not document these commands: %s\n"+
			"Add a `weftly <name> ...` line for each.", strings.Join(missing, ", "))
	}
}

// TestREADMEDocumentsEveryFlag fails when a flag exists on some command
// but appears nowhere in the reference block.
//
// Membership is checked against the whole block rather than per-command:
// attributing a flag to its command would mean parsing the block's
// indentation structure, and the drift that actually happens is "a new
// flag was added and written down nowhere at all".
func TestREADMEDocumentsEveryFlag(t *testing.T) {
	block := readmeCLIBlock(t)
	cmds := map[string][]string{}
	walk(NewRootCmd(), cmds)

	type miss struct{ cmd, flag string }
	var missing []miss
	for cmd, flags := range cmds {
		for _, f := range flags {
			if !strings.Contains(block, "--"+f) {
				missing = append(missing, miss{cmd, f})
			}
		}
	}
	sort.Slice(missing, func(i, j int) bool {
		if missing[i].cmd != missing[j].cmd {
			return missing[i].cmd < missing[j].cmd
		}
		return missing[i].flag < missing[j].flag
	})
	if len(missing) > 0 {
		var lines []string
		for _, m := range missing {
			lines = append(lines, "  weftly "+m.cmd+" --"+m.flag)
		}
		t.Errorf("README `## CLI` block does not document these flags:\n%s",
			strings.Join(lines, "\n"))
	}
}

// TestREADMEHasNoStalePhaseLanguage guards the other half of the drift
// that actually happened: the intro described shipped features
// (the server, DAG parallelism, --resume, a `prompt` stub) as future
// work for over three phases.
func TestREADMEHasNoStalePhaseLanguage(t *testing.T) {
	body, err := os.ReadFile(filepath.Join("..", "..", "README.md"))
	if err != nil {
		t.Fatal(err)
	}
	s := string(body)
	for _, stale := range []string{
		"are Phase 2",
		"is a Phase 2 feature",
		"Phase 1 ships",
		"stub reserves the action name",
	} {
		if strings.Contains(s, stale) {
			t.Errorf("README still contains stale roadmap language %q — "+
				"these features shipped; describe what the tool does, not what it will do", stale)
		}
	}
}
