package cli

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

// initTemplate is the file we write. Deliberately tiny — an operator
// scrolling the file for the first time can read and understand it in
// one screen. Every field they'd need to grow into (env, defaults,
// retry, container, cleanup) is present as a commented pointer.
const initTemplate = `# %s.yml — weftly workflow (generated by 'weftly init')
name: %s
description: "TODO: what does this workflow do"

# inputs:
#   env_url:
#     description: base URL to hit
#     required: true

# env:
#   REGION: us-east-1

# defaults:
#   shell: bash

steps:
  - id: hello
    name: Say hi
    run: |
      echo "hello, weftly"
      echo "greeting=hi" >> "$WEFTLY_OUTPUT"

  - id: report
    name: Print outputs
    run: |
      echo "greeting was $GREETING"
    env:
      GREETING: "${{ steps.hello.outputs.greeting }}"

# cleanup:
#   - id: teardown
#     if: ${{ always() }}
#     run: echo "always runs at the end"
`

func newInitCmd() *cobra.Command {
	var out string
	cmd := &cobra.Command{
		Use:   "init <name>",
		Short: "Scaffold a new workflow YAML from a minimal template",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			name := args[0]
			path := out
			if path == "" {
				path = filepath.Clean(name) + ".yml"
			}
			if _, err := os.Stat(path); err == nil {
				return fmt.Errorf("init: %s already exists (pass -o to write elsewhere)", path)
			}
			body := fmt.Sprintf(initTemplate, name, name)
			if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
				return err
			}
			fmt.Fprintf(cmd.OutOrStdout(), "wrote %s\n", path)
			return nil
		},
	}
	cmd.Flags().StringVarP(&out, "out", "o", "", "write the scaffolded file to this path instead of <name>.yml")
	return cmd
}
